version: '3.6'

networks:
   net-db:

services:
   db:
     image: postgres
     restart: always
     environment:
             POSTGRES_PASSWORD: pass
     volumes:
      - './postgres/data:/var/lib/postgresql/data'
     ports:
      - '5432:5432'
     networks:
      - 'net-db'
   go_project:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          IP: localhost
          PORT: 8000
          POSTGRES_URL: 0.0.0.0:5432
          POSTGRES_PASSWORD: pass
      ports:
        - '8000:8000'
      depends_on:
        - 'db'
      networks:
        - 'net-db'
