version: '3.6'

networks:
   net-db:

services:
   db:
     image: postgres
     environment:
      POSTGRES_PASSWORD: pass
     volumes:
      - './postgres/data:/var/lib/postgresql/data'
     networks:
      - 'net-db'
   go_project:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        IP: 0.0.0.0
        PORT: 8000
        POSTGRES_URL: db
        POSTGRES_PASSWORD: pass
      ports:
        - '8000:8000'
      depends_on:
        - 'db'
      links:
        - 'db'
      networks:
        - 'net-db'
